### ISSUE TITLE
Producer/Consumer partition assignments

### ISSUE THREAD

**Issue by adrienmo** [kafkaex/kafka_ex#118]
I am not sure if this is really an issue, but I would like to discuss how the partition assignments are handled with this library. Both `KafkaEx.produce` and `KafkaEx.fetch` require the partition number to perform the request. 

For example: If i have a topic with 20 partitions and 2 consumers belonging to the same consumer_group: It is expected that each consumer will consume 10 partitions each. It seems the library do not offer this level of abstraction yet.

Do you plan on adding this logic of partition assignment later on? Or maybe Kafka 0.9.x will resolve this problem?

At the moment I am using Kafka 0.8.2.1 and performing the partition assignment using Redis (ensuring message being read at least and at most once). If you are interested by the logic I could either : 
- create a wrapper for the kafka_ex library
- integrate the logic in a pull request to this project (maybe with an optional dependency for redis lib)

**Comment by dantswain** [comment]
Hi!  Thanks for the info and questions!

Partition assignment for consumers is part of the 0.9.x work that we're doing - see #67.

Partition assignment for producers is a little different.  Usually that's determined on a per-message basis.  A common strategy is to shard messages across partitions based on timestamp or some other piece of business-related data.  If you want a particular worker to always publish to a particular partition, it should be relatively easy to manage that on your end.  I think there's so many varying use cases that it's not necessarily a good idea for us to try to implement one.

I would say that adding a redis dependency here is a bit out of scope.  If you want to implement a wrapper library, we could probably mention it in the docs and link to it.

FWIW The way I've solved this in production with Kafka 0.8.2.1 (and actually now 0.9 since we don't have the 0.9 features implemented in KafkaEx yet) is to implement a relatively simple lock in zookeeper.  It requires manual partition assignment and it doesn't rebalance when a worker goes down, but it's fairly robust and works for our use case where the workers are relatively stable.

**Comment by cdegroot** [comment]
FWIW, I wonder how you can abuse redis to effect exactly-once-delivery in Kafka. My gut feeling is that there are still plenty of edge cases where it won't work. Always go for idempotency in message delivery, makes life much simpler :)

**Comment by bjhaid** [comment]
I am closing this issue as I assume the concerns has been addressed, if you feel otherwise please reopen
