### ISSUE TITLE
Reading Brokers from  Zookeeper

### ISSUE THREAD

**Issue by leifg** [kafkaex/kafka_ex#130]
I am currently building a little application. I want to be able to read the different brokers from broker (the host names change a lot). I wrapped this in a function (`App.Zookeeper.brokers`).

to pass this is in the start function of KafkaEx, I need to set in the config (all parameters in [start function](https://github.com/kafkaex/kafka_ex/blob/master/lib/kafka_ex.ex#L323) are ignored).

But I can't execute any functions in the config file.

The only way to achieve this is to alter the application environment before starting a kafkaex server:

```elixir
Application.put_env(:kafka_ex, :brokers, App.Zookeeper.brokers)
Application.put_env(:kafka_ex, :consumer_group, "some_name")
KafkaEx.start(:irrelevant, :also_irrelevant)
```

I think it makes more sense to pass the parameters from config file into the start method.

**Comment by dantswain** [comment]
You should be able to disable the default workers so that KafkaEx doesn't attempt to connect on node startup.  Then you can read your brokers from zookeeper and set up workers using `KafkaEx.create_worker`.

The KafkaEx OTP application should be independent of configuration.  The default worker is just provided as a convenience, though admittedly in cases like this it can lead to confusion.

**Comment by bjhaid** [comment]
I am closing this issue as I assume the concerns has been addressed, if you feel otherwise please reopen
