### ISSUE TITLE
Make travis track all kafka_server versions

### ISSUE THREAD

**Issue by bjhaid** [kafkaex/kafka_ex#139]
We currently run CI against only the 0.9.0 server in travis, we should have travis run builds for the 0.8.0 and 0.8.2 servers

**Comment by dantswain** [comment]
Might want to do this within a single build rather than adding a dimension to the build matrix.

Have you considered using Docker for this?

**Comment by bjhaid** [comment]
> Have you considered using Docker for this?

Maybe? Server here refers to the server internal to kafka_ex and not kafka

**Comment by dantswain** [comment]
I mean using docker to spin up Kafka clusters - e.g., run clusters with different versions of kafka.

IIRC I thought about this before but one problem we would run into is that the community images for Kafka have replication enabled by default and a lot of our integration tests fail when the cluster has replication.  They don't fail because the code is doing the wrong thing, but because the tests don't properly handle some of the asynchronous things that happen in a cluster with replication.

**Comment by Argonus** [comment]
Migrated to github actions. And we use newer kafka versions.
