### ISSUE TITLE
Handling Kafka Downtime

### ISSUE THREAD

**Issue by philippneugebauer** [kafkaex/kafka_ex#192]
Is there any way to keep my processes alive even though my kafka server went down?
I couldn't find any settings to enable this behavior.
I don't want to see my worker processes dieing just because kafka crashed but trying to reestablish the connection to send the next messages. 

My application is standalone and just communication its state - so it could run a while without the communication.

**Comment by dantswain** [comment]
I would recommend using a broker cluster so that downtime doesn't become an issue.  

It sounds like you're mainly doing produce requests, which is hopefully a little simpler to deal with than consume.  You could wrap your producer in a process that maintains an "is the broker alive?" state, then wrap the produce request in a try/catch that updates that state.  Alternatively you could maybe just set a ludicrous restart policy.

I'm going to close this issue as it doesn't appear to be reporting any bugs or feature requests.  Feel free to continue to reply here for more discussion or pop onto the #kafkaex channel on http://elixir-lang.slack.com
