### ISSUE TITLE
DefaultPartitioner 

### ISSUE THREAD

**Issue by zapient** [kafkaex/kafka_ex#206]
There should be a partitioner class to that behaves similar to the [Java DefaultPartitioner](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/producer/internals/DefaultPartitioner.java#L54-L71) so that we can deterministically write to the same partition given a key. Adding in default round-robin behavior in the case of no partition or key should also be included.

**Comment by dantswain** [comment]
Thanks for the suggestion, @zapient.

I disagree with the idea that this should be automatic.  I think it masks behavior and doesn't go along with the idea that this is a fairly low-level library.  I think it could, on the other hand, make sense to add a partitioner `behaviour`, provide an implementation module that matches the Java default, and update the documentation to make its use clear.  Would that be an acceptable compromise?

@bjhaid what do you think?

**Comment by zapient** [comment]
That would be great.

**Comment by bjhaid** [comment]
> provide an implementation module that matches the Java default, and update the documentation to make its use clear

I agree on this, however this should be a very simple implementation to demonstrate how folks can plug in their implementation if they need to

**Comment by zapient** [comment]
> however this should be a very simple implementation

Agreed. Luckily the java implementation is pretty straightforward with the exception of the Murmur hashing algorithm. Not sure how you feel about adding in external dependencies but there is already an [existing implementation](https://github.com/gmcabrita/murmur) of this.

**Comment by dantswain** [comment]
Hm. The java implementation has a state - it basically steps through the available partitions for a given topic, so it has to have a running global counter for each topic .  I'd really like to avoid introducing more state if it's at all possible.  For example, at work we either just modulo a random number or modulo the timestamp.  It isn't always _perfectly_ balanced but it's good enough for us in production.  It would still be totally possible for someone to implement the stateful partitioner, but I really wouldn't want to suggest that out-of-the-box since it could very well have performance implications.

When a key is given, they use murmer for hashing.  Would it be acceptable to use another hash algorithm that is baked into the erlang stdlib?  I don't know the practical implications.

**Comment by zapient** [comment]
> For example, at work we either just modulo a random number or modulo the timestamp. It isn't always perfectly balanced but it's good enough for us in production.

If a behavior is defined it should be trivial for anyone wanting that exact behavior to implement themselves so that really isn't a concern.

> When a key is given, they use murmer for hashing. Would it be acceptable to use another hash algorithm that is baked into the erlang stdlib? I don't know the practical implications.

I'm not too familiar with implications of that either. It could be a problem if one assumes that all events are ordered for a given key and both a Java and KafkaEx client are writing those events but I wouldn't think that is a valid use case. As long as the partition assignment is deterministic it would solve my problems :)
