### ISSUE TITLE
offset_out_of_range error when starting a consumer group

### ISSUE THREAD

**Issue by thecodeboss** [kafkaex/kafka_ex#258]
When starting a consumer group, there should be a check that the consumer group offset is larger than the earliest offset available in Kafka.

For example, currently if a consumer group offset is 0, but Kafka's earliest offset is 100, it's impossible to start up a `KafkaEx.ConsumerGroup` without first requesting changes to the consumer group offset, since 

**Proposed solution:**

When consuming messages in a `KafkaEx.GenConsumer`, if an `:offset_out_of_range` error is encountered, it should automatically update the consumer offset to the earliest offset available rather than simply crashing.

**Comment by dantswain** [comment]
Thanks for the issue @thecodeboss!

If I understand correctly, I'm not sure that this is something that we should handle automatically.  If you are running a consumer group and your consumer's offsets are out of range, you probably want to know that rather than have the worker quietly start consuming from the earliest offset available.  Kafka provides tools to manage consumer group offsets in situations like this.  It's also possible to `commit` the offset manually using KafkaEx.

It could be that what we should do is provide some kind of callback mechanism so that the user can decide what to do here.

**Comment by thecodeboss** [comment]
@dantswain the callback mechanism would definitely be helpful.

Right now our approach during startup is to first edit our consumer offset before doing `Supervisor.start` on the `KafkaEx.ConsumerGroup`. But we still run into cases where the consumers don't keep up and things crash. It also seems like manual and unnecessary work, since the consumer should be smart enough to not request data that doesn't exist.

In `KafkaEx.GenConsumer.consume/1`, there's a match on `:no_error`, and so it always crashes without any grace when there's an `:offset_out_of_range`.

**Comment by thecodeboss** [comment]
Looking at the [kafka-python repo](http://kafka-python.readthedocs.io/en/master/apidoc/kafka.consumer.html?highlight=auto_offset_reset#kafka.consumer.KafkaConsumer), it seems the way that library handles this is to have a parameter when creating the consumer called `auto_offset_reset`. You can then specify a policy for how to handle the errors automatically.
Perhaps `KafkaEx.GenConsumer` could support a similar option.

**Comment by joshuawscott** [comment]
Closing as this was fixed in #266
