### ISSUE TITLE
How to handle changing brokers, or not knowing brokers at startup

### ISSUE THREAD

**Issue by craig-day** [kafkaex/kafka_ex#265]
I've been working with this for a while and one pain point is that the kafka_ex otp app wants the brokers to be there on startup.  In the case of my application, I look up the available kafka brokers from a [consul service catalog](https://www.consul.io/api/catalog.html) during the start of my application. This become a problem because my application doesn't start until after the otp apps of my dependencies start, so I don't know this information in time. 

Any thoughts on how to configure brokers during runtime? Maybe even have a config change callback so the brokers can be changed after the app has started up. 

I hope this makes sense, and would love to discuss ways to approach the lack of information before the app starts.

**Comment by dantswain** [comment]
Hi @craig-day !    This isn't documented super well (I had to dig for a few minutes to find it myself), but I think this _should_ be doable without any changes to the library.  If you're using workers bare, you can pass in uris as an option to `KafkaEx.create_worker`.  If you're using consumer groups, you can pass the uris option along in its options.  I.e., if you check out the [ConsmerGroup documentation](https://hexdocs.pm/kafka_ex/KafkaEx.ConsumerGroup.html#content), you could modify it with something like this:

```
    consumer_group_opts = [
      # setting for the ConsumerGroup
      heartbeat_interval: 1_000,
      # this setting will be forwarded to the GenConsumer
      commit_interval: 1_000,
      # fetch uris from consul
      uris: get_uris_from_consul()
    ]
```

As far as dealing with changing brokers, I'd say that falls under "fail fast".  The OTP of handling that would be to crash the running workers and restart new ones using the new uris.  This is a little complicated with Kafka because the `uris` is actually just a list of seed brokers and the first one you successfully connect to will respond with a list of brokers in the cluster.  KafkaEx actually has some of this baked in - it is supposed to deal with changing lists of brokers on the metadata update cycle.  I'm not sure if anyone has actually tested that in production, though, and I'd be really interested to hear any reports.

**Comment by craig-day** [comment]
Thats awesome. Thanks for the quick reply. I will test out these options and let you know how it goes. Feel free to close this issue in the meantime, and I'll just drop a comment on here after I've done some investigation.

**Comment by dantswain** [comment]
Thanks, @craig-day !  I'll go ahead and close this, but we'd be glad to hear your findings.  Feel free to open more issues if you have any follow-up or run into any problems!  Also feel free to ping us on the #kafkaex chat on elixir-lang.slack.com.
