### ISSUE TITLE
KafkaEx.ConsumerGroup is not scalable

### ISSUE THREAD

**Issue by gabiz** [kafkaex/kafka_ex#308]
KafkaEx.ConsumerGroup cannot scale to large number or topics/partitions.

**How to replicate**

Launch kafka docker:

```bash
$ ./scripts/docker_up.sh
```

Create topic with say 100 partitions

```bash
$ docker-compose exec kafka3 /bin/bash -c "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 KAFKA_PORT=9094 KAFKA_CREATE_TOPICS=my_topic:100:2 create-topics.sh"
```

Create mix project with default config and `ExampleGenConsumer` from documentation and the following supervisor:

```elixir
defmodule KL do
  use Application

  def start(_type, _args) do
    import Supervisor.Spec, warn: false

    Supervisor.start_link(
    [supervisor(
         KafkaEx.ConsumerGroup, [ExampleGenConsumer, "my_group", ["my_topic"], []]
      )
    ], strategy: :one_for_one, name: KL.Supervisor)
  end
end
```

Run project and launch observer. Without even sending or receiving messages the Scheduler Utilization gets close to 100%.

<img width="477" alt="screen shot 2018-09-11 at 9 27 28 pm" src="https://user-images.githubusercontent.com/371924/45402275-aee4ef00-b609-11e8-9cb0-5185bbe0fee8.png">

**Comment by joshuawscott** [comment]
@gabiz were you able to try this out to see if it resolved the issue?

**Comment by joshuawscott** [comment]
Closing because I believe it is resolved by a configuration change.

**Comment by mtrudel** [comment]
@joshuawscott do you have any insight into any operational risks of using a much larger (around 10s or so) value for this?

We use Kafka as a backing queue, but our use is a little different than most Kafka environments (we provide an on-prem app that's hosted within a single VM). Specifically, we don't make any explicit use of multiple servers or partitioning, and only very modest use of multiple consumers within a given consumer group. It would seem to me in this case that much larger values would be indicated in our environment, but I have to confess to being rather ignorant of any issues this may present within Kafka's byzantine network environment. Any guidance?

**Comment by joshuawscott** [comment]
@mtrudel There's no issue unless you are doing `GenServer.call`s into the GenConsumer. In that case, you would need to take care that you increase those timeouts to more than the 10 seconds the GenConsumer would be potentially blocked waiting on a response from the broker.

I'm not completely sure if the kafka broker has a timeout related to this or not.

I don't think increasing wait_time is indicated if you have few partitions and consumers.

In general, I don't see much use for increasing the wait_time beyond 1 second if you do not have a very large volume of partitions. The `wait_time` by default is only encountered if we attempt to fetch messages from kafka, and there aren't any. You could also encounter the `wait_time` if you have configured `min_bytes` to be higher than the default `1`. In either case, calling `KafkaEx.fetch/3` will wait up to `wait_time` milliseconds for `min_bytes` bytes to be available from the broker. 

At the default of 10ms, the `wait_time` causes a lot of calls to be made as the GenConsumer loops tightly requesting messages from the broker and timing out (assuming that there are no messages). Otherwise, it just fetches the available messages up to `max_bytes` (default 1MB) and then handles them. Once the `handle_message_set/2` callback returns, it would then immediately do another fetch regardless of wait_time.

Hope this helps!

**Comment by mtrudel** [comment]
It helps immensely, thank you! We're generally using Kafka as an adjunct to our main app (and even then in a rather off-label fashion), so it's hard for us to know what typical Kafka defaults make sense in our case or not. 

Generally, we're using it as a simple low volume, high fanout queueing system with lots of low volume queues (some are empty for hours or days at a time) and multiple single-worker consumer groups, so paying the busy wait overhead at 10ms was killing us. Raising it as low as 1s almost entirely alleviates the issue for us. 

FWIW, it seems that delays over the default 5s GenServer timeout do indeed cause breakage within kafka_ex as you suspected (not that that's a problem for us; 1s is plenty long enough for our needs). 

Thanks again!
