### ISSUE TITLE
Kayrock based client doesn't handle tcp_closed

### ISSUE THREAD

**Issue by kennethito** [kafkaex/kafka_ex#381]
```
GenServer :pn_kafka_worker terminating
** (FunctionClauseError) no function clause matching in KafkaEx.New.Client.handle_info/2
    (kafka_ex) lib/kafka_ex/new/client.ex:187: KafkaEx.New.Client.handle_info({:tcp_closed, #Port<0.115858>}, %KafkaEx.New.Client.State{
```

This is happening periodically on what looks like a regular interval.  I'm using master at https://github.com/kafkaex/kafka_ex/tree/c93ce47472bff36c41b7c2fa3920449ca342ef8f 

It's not latest, but a brief inspection of latest doesn't look to be handling the message either?

**Comment by pixelvitamina** [comment]
@joshuawscott any hint to fix this issue? thank you!

**Comment by dantswain** [comment]
I've been observing this myself.  AFAICT it's generally harmless - the broker appears to close the connection, which causes the GenServer to crash and restart.  Arguably this is what should happen idiomatically for the Erlang VM as we would "fail fast" and not try to recover any potentially bad state due to the closed connection.  It may be appropriate for it to not emit an error log, however.  I'll be thinking about this.
