### ISSUE TITLE
Investigate alternatives to travis-ci

### ISSUE THREAD

**Issue by dantswain** [kafkaex/kafka_ex#421]
Travis-CI seems to be getting noticeably slower for OSS builds: https://www.traviscistatus.com/#month

I've definitely noticed significant queue times for builds, which is a pretty major slowdown for iterating on PRs.  Furthermore, using travis has caused some difficulty in the test suite because the instances it runs are somewhat anemic and that can make running the tests and kafka at the same time fairly rough.

Alternatives that I have a some amount of familiarity with off-hand:
* Github actions
* CircleCI
* GitLab (can we do this without moving the project?)

I'm open to opinions here, though I'll be favoring platforms that the core maintainers are comfortable with.  @joshuawscott @jbruggem @bjhaid

**Comment by jbruggem** [comment]
Excellent initiative !

I have a tiny bit of experience with Github actions, and a lot of experience with Gitlab CI (that what we use at my company).

My opinion is that we should consider first Github actions. There's a strong added value in having everything in one tool ! My experience with it was good.


If it doesn't pan out, I can voutch for GitlabCI (though I have experience with it on-prem, so I don't know the performance it has for free accounts on their cloud version).  Not sure about how we could integrate the CI status in Github though :thinking: . In that case, I'd recommend using their `services` system rather than a docker-compose, which will be more efficient. We'd keep the docker-compose setup locally.

**Comment by dantswain** [comment]
I gave github actions a try for kayrock and it was pretty easy and builds pretty fast.  https://github.com/dantswain/kayrock/blob/master/.github/workflows/elixir.yml

The hard part will be kafka of course
